web:
  build: .
  ports:
    - "8080:8080"
  volumes:
    - ./app:/app
  links:
    - mongodb
  environment:
    - FLASK_APP=/app/app.py
    - MONGO_HOST=mongodb
mongodb:
  ports:
    - "27017:27017"
  image: mongo
  command: --smallfiles